### ISSUE TITLE
Calibration priors?

### ISSUE THREAD

**Issue by mraveri** [ACTCollaboration/DR6-ACT-lite#12]
I cannot find priors for Planck calibration and ACT polarization efficiency in the yaml files.

How should these be set to reproduce the paper's results?

Planck should probably be:

A_planck:
    prior:
      dist: norm
      loc: 1
      scale: 0.0025
    ref:
      dist: norm
      loc: 1
      scale: 0.002
    proposal: 0.0005
    latex: y_\mathrm{cal}
    renames: calPlanck

?

**Comment by cmbant** [comment]
PlanckActCut seems to have A_Planck in the yaml.
but cf https://github.com/ACTCollaboration/DR6-ACT-lite/issues/11

Their chain yamls have

```
prior:
  cal_dip_prior: 'lambda A_act: stats.norm.logpdf(A_act, loc = 1.0, scale = 0.003)'
 A_planck:
    prior:
      min: 0.5
      max: 1.5
    ref:
      dist: norm
      loc: 1.0
      scale: 0.1
    latex: A_{\rm planck}
    proposal: 0.003
A_act:
    value: 'lambda A_planck: A_planck'
    latex: A_{\rm ACT}
    derived: true
P_act:
    prior:
      min: 0.9
      max: 1.1
    ref:
      dist: norm
      loc: 1.0
      scale: 0.01
    proposal: 0.01
    latex: p_{\rm ACT}
```

So my understanding is that if you combine with Planck, A_act gets the Planck prior 1\pm 0.0025 on A_planck AND the prior 1\pm 0.003 from ACT. Is this right, seems weird?? (though I'm sure makes almost no difference)

**Comment by HTJense** [comment]
Correct, the setup is indeed a bit counter-intuitive perhaps, but the correct prior (as implemented) is found by looking in `yamls/likelihoods/p_act_lite.yaml`:

```
act_dr6_cmbonly.PlanckActCut:
  params:
    A_planck:
      prior:
        min: 0.5
        max: 1.5
      ref:
        dist: norm
        loc: 1.0
        scale: 0.1
      latex: A_{\rm planck}

act_dr6_cmbonly.ACTDR6CMBonly:
  params:
    A_act:
      value: "lambda A_planck: A_planck"
      latex: A_{\rm ACT}
```

So we calibrate ACT and Planck with their respective parameters fixed to each other. Then, in the file `p-act-lb-lcdm.yaml` we set the prior:

```
prior:
  cal_dip_prior: 'lambda A_act: stats.norm.logpdf(A_act, loc = 1.0, scale = 0.003)'
```

So yes, I agree that it is written a bit backwards that we fix A_act while varying A_planck, but set the prior to A_act instead.

(note that there should not be any informative prior on the calibration efficiency `P_act`).

**Comment by HTJense** [comment]
The ACT power spectra are calibrated off the Planck dipole measurement, hence the parameters encapsulate the same calibration uncertainty. See page 25 of [Louis et al.](https://arxiv.org/abs/2503.14452).

**Comment by HTJense** [comment]
I have implemented my earlier suggestion in #13, leaving the prior on the freely-sampled A_act parameter, whilst fixing A_planck = A_act when combining in the P-ACT combination.

**Comment by cmbant** [comment]
I would have thought the natural thing to do was have PlanckActCut as now, then in ACTDR6CMBonly.yaml have

```
  params:
    A_planck:
      prior:
        dist: norm
        loc: 1
        scale: 0.0025
      ref:
        dist: norm
        loc: 1
        scale: 0.002
      proposal: 0.0005
      latex: y_\mathrm{cal}
      renames: calPlanck
    A_act:
      value: "lambda A_planck: A_planck"
      latex: A_{\rm ACT}
    P_act:
      prior:
        min: 0.9
        max: 1.1
      ref:
        dist: norm
        loc: 1.0
        scale: 0.01
      proposal: 0.01
      latex: p_{\rm ACT}
```

All with no cal_dip_prior (assuming I interpreted what you are aiming for correctly).
 
Then you could combine the two likelihoods as you like without using any of /yaml file overrides? (and also self-consistently e.g. combine planck_2018_lowl.TT + ACT if you wanted to). As long as the A_planck blocks are the same, can combine as many likelihoods as you like with the same setting, as for the Planck likelihoods.

I was naively just trying to use them without looking in your yamls, as you can for other likelihoods. e.g.

```
   likelihood:
     planck_2018_lowl.TT:
     planck_2018_lowl.EE_sroll2:
     act_dr6_cmbonly.PlanckActCut:
     act_dr6_cmbonly.ACTDR6CMBonly:
```
